### ISSUE TITLE
[Bug] in Gemfile parser

### ISSUE THREAD

**Issue by rmetzler** [versioneye/versioneye#414]
When I use [this Gemfile](https://github.com/refinery/refinerycms/blob/master/Gemfile) to create a new project the following happens:
![bildschirmfoto 2013-12-13 um 14 47 56](https://f.cloud.github.com/assets/58824/1742503/3d2b8e5e-63fd-11e3-8fac-4348d4ade96c.png)

**Comment by reiz** [comment]
@rmetzler This issue was fixed today. Now the same Gemfile looks like this on VersionEye: 

![screen shot 2016-07-06 at 09 15 38](https://cloud.githubusercontent.com/assets/652130/16610239/53bc3792-435a-11e6-9062-3f31aaa44253.png)
