### ISSUE TITLE
Gemfile improvements

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye#416]
Make this Gemfile work: 
https://github.com/refinery/refinerycms/blob/master/Gemfile

**Comment by reiz** [comment]
We integrated the Gemansium parser and have now support for gemspecs. Versions referencing GIT or PATH are not supported, but that's OK because this kind of references are anyway custom code.

**Comment by PikachuEXE** [comment]
I will see no dependencies for my gem projects...
[Project repo](https://github.com/PikachuEXE/where_lower)
[Version Eye Page for that project](https://www.versioneye.com/user/projects/5163a9663f7f800002003767)
![screen shot 2018-03-22 at 9 46 10 am](https://user-images.githubusercontent.com/1018543/37746578-e557ff00-2db5-11e8-87d8-90d4a71dac15.png)
