### ISSUE TITLE
Error when importing new setup.py / ez_setup.py from Bitbucket

### ISSUE THREAD

**Issue by rmetzler** [versioneye/versioneye#434]
I tested the Bitbucket integration and the only project I have there is pygments, which I forked. https://bitbucket.org/rmetzler/pygments-main/src

I want to add setup.py or ez_setup.py and I don't know if there are dependencies inside or not. I just get this error.

![bildschirmfoto 2014-01-02 um 19 09 38](https://f.cloud.github.com/assets/58824/1834270/0565be30-73da-11e3-9217-5e79b04fd5ea.png)

**Comment by reiz** [comment]
@rmetzler Should be fixed by now. If not feel free to reopen this ticket.
