### ISSUE TITLE
order packages and versions in update email

### ISSUE THREAD

**Issue by rmetzler** [versioneye/versioneye#440]
currently update emails about packages you follow look like this:
![screenshot_2014-01-06-12-43-42](https://f.cloud.github.com/assets/58824/1850193/82f2de78-76c8-11e3-8a0c-a7f9eec76df7.png)

it would be great to see all Hibernate updates next to each other.
This is a simple example, I've seen much more scattered emails.

**Comment by reiz** [comment]
That's fixed already. Currently only the newest version is part of the email for the case that a package has several new versions per day.
