### ISSUE TITLE
Adding new projects is (very) unintuitive

### ISSUE THREAD

**Issue by stefan-kolb** [versioneye/versioneye#627]
It took me some time to find this functionality whereas it should be immediately accessible.

Clicking on Projects does only show currently active projects. But no Options to add a new one.
To add a project I have to go to Organizations, select an organization (also it is not clear to me why I need an organization by default), and only then I'm able to add new projects.
![image](https://cloud.githubusercontent.com/assets/2141507/17134088/09e7c44a-5329-11e6-898e-6e346c8701d6.png)

Also, the + button on the very top suggests it adds projects but not suggests a new package.
![image](https://cloud.githubusercontent.com/assets/2141507/17134104/23577754-5329-11e6-8668-869398731f26.png)

**Comment by reiz** [comment]
@stefan-kolb Ok. I'm kind of "Betriebsblind" for my own tool. You think it would be better to have a big "Create New Project" button in the main menu?

**Comment by stefan-kolb** [comment]
I don't have a perfect solution in my mind yet, but I just wanted to point out that it was really hard to find for me how to add an existing project from Github via the UI. At least I expected it to be under projects and not inside the organizations.

**Comment by reiz** [comment]
OK. That feedback is already very valuable.

**Comment by stefan-kolb** [comment]
I'll also ask a few of my colleagues the next days.

**Comment by reiz** [comment]
It makes sense what you say. I will add it to the main menu. It must be dead easy to add a new project.

**Comment by reiz** [comment]
@stefan-kolb I just added a new link to the main menu. 

<img width="1148" alt="screen shot 2016-08-02 at 23 08 02" src="https://cloud.githubusercontent.com/assets/652130/17345461/7d2d1c6a-5906-11e6-9133-2aea757a9169.png">

What do you think? Good?

**Comment by stefan-kolb** [comment]
LGTM :+1:
