### ISSUE TITLE
Maven plugin and PDF/CSV reports

### ISSUE THREAD

**Issue by kyuff** [versioneye/versioneye#632]
It would be really convenient for the build tools to be able to download the reports (pdf/csv) as part of running mvn versioneye:update.

The usecase is to have a build server be able to store artifacts from the build, which would include Bill of Materials.

**Comment by reiz** [comment]
Hey @kyuff, that's a good idea. Maybe oben this ticket directly here: https://github.com/versioneye/versioneye_maven_plugin. 

The license PDF report can be downloaded always with this URL: 

```
/user/projects/PROJECT_ID/lwl_export
```

That will succeed if you have the right permission. On VersionEye Enterprise that should succeed always.
