### ISSUE TITLE
Links to licenses in PDF Bill of Materials

### ISSUE THREAD

**Issue by kyuff** [versioneye/versioneye#633]
The PDF contains a section like this:

Bill of materials:
- Apache License 2.0
- Apache License 1.1
- Apache License 1.0
- MIT License
- Common Development and Distribution License 1.0
- Common Development and Distribution License 1.1

It would be really great to enhance this list to include links to the license text for the given licenses.

This would fullfill the requirement of many of the licenses, that states the text should be available with the using software.

**Comment by reiz** [comment]
@kyuff Ok. That can be added here: https://github.com/versioneye/versioneye-core/blob/master/lib/versioneye/views/lwl_pdf/lwl_pdf.html.erb#L172. Can work on that next week.

**Comment by reiz** [comment]
@kyuff this is done now. The licenses in the PDF are now clickable! They are clickable for standard licenses and for licenses there we have an URL for. Some exotic license names are not clickable.
