### ISSUE TITLE
Failed to start rails server

### ISSUE THREAD

**Issue by Neola** [versioneye/versioneye#634]
hi,
 I installed the develop versioneye, and after all dependencies installed,
##  run "rails s" with below errror,

W, [2016-08-05T13:53:36.679392 #4457]  WARN -- : Creating scope :parents. Overwriting existing method Project.parents.
/usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye/model.rb:31:in `require': /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye/models/language_daily_stats.rb:147: syntax error, unexpected ':', expecting => (SyntaxError)
...ersions.created_at' => {'$lte': until_date } } },
...                               ^
/usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye/models/language_daily_stats.rb:149: syntax error, unexpected ']', expecting keyword_end
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye/model.rb:31:in`class:Model'
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye/model.rb:2:in `<module:Versioneye>'
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye/model.rb:1:in`<top (required)>'
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/settings.rb:3:in `require'
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/settings.rb:3:in`<top (required)>'
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye-core.rb:8:in `require'
        from /usr/local/share/gems/bundler/gems/versioneye-core-2fe4245e6b21/lib/versioneye-core.rb:8:in`<top (required)>'
        from /root/versioneye-develop/config/application.rb:3:in `require'
        from /root/versioneye-develop/config/application.rb:3:in`<top (required)>'
        from /usr/local/share/gems/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /usr/local/share/gems/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:78:in`block in server'
        from /usr/local/share/gems/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /usr/local/share/gems/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:75:in`server'
        from /usr/local/share/gems/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/share/gems/gems/railties-4.2.7/lib/rails/commands.rb:17:in`<top (required)>'
        from bin/rails:9:in `require'
##         from bin/rails:9:in `<main>'

could you help to check it?

**Comment by reiz** [comment]
Hi @Neola. Is this problem still current? Which Ruby version are you using and which OS? It works fine for me ;)

**Comment by reiz** [comment]
Hi @Neola if this is still an issue please open a ticket in this repo: https://github.com/versioneye/ops_contrib.
