### ISSUE TITLE
Suggestions for licenses for products with UNKNOWN license

### ISSUE THREAD

**Issue by jcgjunge** [versioneye/versioneye#635]
It would greatly improve the usability of versioneye, if it was possible to suggest a license for a product. 

We are currently using some older third party products, for instance https://www.versioneye.com/java/org.springframework:spring-context/3.0.7.RELEASE and we can not use the report from versioneye, if the license is UNKNOWN. 

Therefore it would be very useful to be able to suggest a license, which could be used for the product until versioneye can confirm/update it. Maybe the suggestion could be scoped to only be active for a specific organisation/team/project, to not contaminate other organisations reports, with wrong information.

**Comment by reiz** [comment]
Hey @jcgjunge I just added the license for that old spring project. But in general you are right. It should be possible to suggest a license.

**Comment by reiz** [comment]
Hi @jcgjunge now you can suggest new licenses. See here: https://blog.versioneye.com/2017/01/18/suggest-new-licenses/. We have even an API Endpoint for it.
