### ISSUE TITLE
NPM public scoped packages

### ISSUE THREAD

**Issue by deeweey** [versioneye/versioneye#637]
Hi,

I couldn't find an issue about this and I'm not sure what's possible with the NPM registry but do you guys have plans or ideas about supporting public scoped NPM packages?

An example is @angular/router.

**Comment by reiz** [comment]
Hi @deeweey. We would love to support that. Do you know how this public scoped packages can be read via the NPM API? I couldn't find much in the docs about that.

**Comment by deeweey** [comment]
I think I found it, at https://github.com/npm/npm/blob/master/lib/utils/map-to-registry.js#L16 they're replacing the / in the registry url.

https://registry.npmjs.org/@angular%2frouter does give a valid response.

**Comment by deeweey** [comment]
Hi, is there anything I can do to help? The crawlers are not in this repo anymore right?

**Comment by reiz** [comment]
Hi @deeweey. This is implemented now. Let us know if it works for you. If it doesn't work like expected feel free to reopen this ticket.

**Comment by deeweey** [comment]
Hi @reiz, thank you for this. 

Could it be that only some packages are whitelisted? If I search for @angular/common it works, but it doesn't show any results for @ng-bootstrap/ng-bootstrap or @angular/cli for instance.

**Comment by reiz** [comment]
Hi @deeweey Not sure what you mean. Can you give an example?
