### ISSUE TITLE
Pull Request feature not respecting Component Whitelists

### ISSUE THREAD

**Issue by MichaelGooden** [versioneye/versioneye#638]
I have a (private, sorry cant share) project who has multiple internal dependencies whose licenses are set to 'proprietary'. VersionEye converts this license into UNKNOWN. Adding these specific dependencies to a component whitelist for the project fixes most of the issues.

The new Pull Request feature does not appear to take this whitelist into account, and instead is failing all pulls with the error "Some dependencies have no license." While this error message is correct, I understand the expected behaviour is to ignore those dependencies as they are listed on a component whitelist set for the project.

I am happy to provide the project ID to any VersionEye staff member if you wish to look at the internal data.

**Comment by reiz** [comment]
Hi @MichaelGooden that's correct. Currently the pull request integration does not take the license whitelist into account. That support is coming this week. Please send your project id to reiz[AT]versioneye.com.

**Comment by tinkerware** [comment]
I have this issue as well; it is annoying to see the VersionEye check fail for each PR.

**Comment by MichaelGooden** [comment]
@tinkerware This problem was actually solved ages ago but it required the correct config setup for it to work.

> The component whitelist is always an extension for the license whitelist. Assume you are putting 'MIT' and 'Apache-2.0' on your license whitelist and some of your dependencies have a 'GPL-2.0' license, then that would violate your license whitelist. But if you put that component on the component whitelist it will become green, even if it violates your license whitelist and those components are marked by a "thumb". See here: https://blog.versioneye.com/2015/09/02/improved-componente-whitelist/
> Another advantage of the component whitelist is that you can whitelist whole groups and namespaces with it. Specially good if you have a lot of in house components who start with the same namespace, but don't have a license. That can be easily whitelisted through the component whitelist.
