### ISSUE TITLE
wrong new version for org.testng:testng

### ISSUE THREAD

**Issue by jinahya** [versioneye/versioneye#639]
Version eye reports a wrong out of dates.

`testng	6.9.10	 6.9.12	Apache-2.0`

which is not in central.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.testng%22%20AND%20a%3A%22testng%22
http://repo1.maven.org/maven2/org/testng/testng/

**Comment by reiz** [comment]
Hi @jinahya It's not a bug. If you check out the download links at VersionEye you will see that it leads to jCenter: http://jcenter.bintray.com/org/testng/testng/. But we stopped crawling jCenter. So that shouldn't be a problem in future.

**Comment by franklinyu** [comment]
@reiz Any blog/comment for reason of not crawling jCenter?
