### ISSUE TITLE
License for Github branches (non-stable)

### ISSUE THREAD

**Issue by herodrigues** [versioneye/versioneye#645]
I'm trying to add a branch of UglifyJS2, but it says there is no license.

![image](https://cloud.githubusercontent.com/assets/1832537/18397265/c614d968-769d-11e6-9dce-9bb821258a7d.png)

However, there is a license! It seems that Versioneye is not parsing dependencies which are not official. Is there any workaround?

**Comment by herodrigues** [comment]
It seems that there is no solution yet. A workaround is just to set this dependency in CI environment, thus it is not necessary to add it to package.json.

```json
"prebuild": "npm install git://github.com/mishoo/UglifyJS2.git#harmony && npm run test",
```

**Comment by reiz** [comment]
Hi @herodrigues Another solution would be to put that dependency on the component whitelist.
