### ISSUE TITLE
NPM libraries with an @ in the name are mishandled

### ISSUE THREAD

**Issue by mithrandi** [versioneye/versioneye#646]
For example, [@kadira/storybook](https://www.npmjs.com/package/@kadira/storybook) shows up as unknown.

**Comment by herodrigues** [comment]
https://www.versioneye.com/Node.JS/getstorybook/1.4.5

**Comment by mithrandi** [comment]
Since I originally ran into this on a private repository, here's a trivial reproduction using a public one:

https://www.versioneye.com/user/projects/57f1619016c6300045abbc72

**Comment by herodrigues** [comment]
You can create a license whitelist and add storybook on it. No a great solution,but It solves problems with CI platforms if you are requiring versioneye statuses in order to merge PRs.

**Comment by reiz** [comment]
Hi @mithrandi @herodrigues we added support for `@` NPM packages a couple week ago. It should work now. If there are still issues with this please feel free to reopen this ticket.
