### ISSUE TITLE
VersionEye doesn't see effective-pom

### ISSUE THREAD

**Issue by jinahya** [versioneye/versioneye#647]
I have a pom type artifact which uses parent's property value as one of its plugin version.
https://www.versioneye.com/user/projects/56542ba4ff016c002c000899

``` xml
$ mvn help:effective-pom
...
 <properties>
    <maven-javadoc-plugin.version>2.10.4</maven-javadoc-plugin.version> <!-- inherited from the parent -->
  </properties>
...
  <build>
    <pluginManagement>
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <!--<version>${maven-javadoc-plugin.version}</version> -->
        <version>2.10.4</version> <!-- substituted normally -->
      </plugin>
    </pluginManagement>
  </build>
...
```

VersionEye is saying the value `${maven-javadoc-plugin.version}` is outdated.

**Comment by cdeszaq** [comment]
I believe the general recommendation is to use the maven versioneye plugin for this, though I've yet to figure out how using the maven plugin works with pull requests.

**Comment by reiz** [comment]
Hi @jinahya This is not a bug, it works like designed. The pom parser on the server can only handle simple pom.xml files, but not Maven reactor builds. If you have a more complex Maven project with multiple pom.xml please use the [VersionEye Maven Plugin](https://github.com/versioneye/versioneye_maven_plugin).
