### ISSUE TITLE
LDAP Bind DN

### ISSUE THREAD

**Issue by bassrock** [versioneye/versioneye#650]
I recently setup version eye however I do not see how to set a bind dn user and password to access our companies corporate directory.

Does version eye fully support a bind dn?

**Comment by reiz** [comment]
Hi @bassrock. Yes. If you are hosting your own VersionEye instance you can connect it to your LDAP or ActiveDirectory server. We have multiple clients who use it that way. If you are logged in as Admin, simply go to Settings => LDAP Settings. Here you will find a form like this one to configure your LDAP. 

<img width="1157" alt="screen shot 2017-01-31 at 14 05 00" src="https://cloud.githubusercontent.com/assets/652130/22465955/6ba3e586-e7be-11e6-8212-801f5d48f2af.png">

**Comment by Mazorius** [comment]
Hallo @reiz,

But where can I configure the user needed to read information from our AD?
If I press "Test Auth.", then no error occurs, but with the "Sign In" form I can not log on.

Best regards
Ron

**Comment by reiz** [comment]
Hi @Mazorius, 

It doesn't work that way. You don't need to configure a single user to read information from AD. You configure a login pattern which can lead to any user in your AD server. If it's configured the right way you are using your AD login credentials at the VersionEye sign in process and the VersionEye server will use your login credentials to read your username and email from the AD server. That happens with every user which logs in. 
In the LDAP Settings page you can use your login credentials for a "Test Auth." and if everything is configured correctly you should get a green success message. 

Best regards, 
Robert
