### ISSUE TITLE
License not assigned correctly to java/com.github.andrewoma.dexx:collection/0.6

### ISSUE THREAD

**Issue by codebje** [versioneye/versioneye#651]
Version 0.5 of com.github.andrewoma.dexx:collection has correctly picked up the MIT license, however the 0.6 version reports UNKNOWN.  The license portion of the POM didn't change between releases.

https://www.versioneye.com/java/com.github.andrewoma.dexx:collection/0.6

https://www.versioneye.com/java/com.github.andrewoma.dexx:collection/0.5

**Comment by reiz** [comment]
OK. I just added the license.
