### ISSUE TITLE
Possibility to ignore missing licenses?

### ISSUE THREAD

**Issue by Guite** [versioneye/versioneye#652]
Hi,

after activating versioneye for a repository all PRs are failing because of *Some dependencies have no license*. Is it possible to configure that this should be ignored?

**Comment by reiz** [comment]
Hi @Guite. Sorry for the late response! Christmas time is always crazy :) 

Currently you can not ignore them directly, but you could set those components on the component whitelist. That way it would be ignored in the next pullrequest check. Here is a blog post about the component whitelist: https://blog.versioneye.com/2015/08/26/component-whitelist/

**Comment by Guite** [comment]
Thanks, will give this a try.
