### ISSUE TITLE
Order statistics by desc

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye#658]
@timgluz The bar chart on the statistic page should be ordered by desc. 

<img width="1081" alt="screen shot 2017-01-19 at 22 24 56" src="https://cloud.githubusercontent.com/assets/652130/22139956/d17bc30c-dee9-11e6-87bc-8e13f2bf2ebf.png">

**Comment by timgluz** [comment]
Done - cause: http://stackoverflow.com/questions/4299062/why-wont-safari-5-sort-an-array-of-objects/4299105#4299105
