### ISSUE TITLE
Lock icon legacy?

### ISSUE THREAD

**Issue by flodnv** [versioneye/versioneye#667]
Hi, I was wondering why the lock icon, indicating a private project, is not showing on our new project. It seems that it should be (their visibility.public was set to `false`) but it's not showing. Any idea why ?

**Comment by reiz** [comment]
Hi @flodnv It's still there for me. See here: 

![screen shot 2017-06-07 at 11 37 48](https://user-images.githubusercontent.com/652130/26872239-26b23c0e-4b76-11e7-8e90-a4d4b53a7483.png)

Can you share a link to your project? I would double check it.

**Comment by flodnv** [comment]
Wellllll.... I assume this bug was fixed because I now see the lock icon where I expect to see it. Thanks for taking a look! 🙇
