### ISSUE TITLE
current version of spring components out of date 

### ISSUE THREAD

**Issue by andyglick** [versioneye/versioneye#668]
One of my versioneye projects can be found here 

https://www.versioneye.com/user/projects/570d35bffcd19a0045440b35#tab-dependencies

all of the spring jars are set to version 4.3.5.RELEASE in the versioneye provided column, and are listed as 4.3.6.RELEASE in the column from my project

checking with maven central the current version is 4.3.6.RELEASE 

why isn't versioneye updating its records for the spring modules?

**Comment by andyglick** [comment]
The version of the spring components available at maven central is now 4.3.7.RELEASE -- I have updated my project here, but versioneye is now referencing the 4.3.6.RELEASE rather than the current version.

Robert, you still haven't answered my original question --  why isn't versioneye updating its records for libraries in maven central?

https://www.versioneye.com/user/projects/570d35bffcd19a0045440b35?utm_medium=email&utm_source=project_notifications

**Comment by andyglick** [comment]
let me make my question a bit more pointed -- you expect people to pay you for this service, but you don't seem to be willing to do the work that paying customers have a right to expect

WTF

**Comment by reiz** [comment]
@andyglick Sorry for the late response! 

VersionEye is crawling Maven Central every day, but Sonatype is updating there Maven index only once a week. Usually on Monday. That means if Spring is released on Tuesday, then we get the information from the Maven central index only on next Monday. 
For all other languages we have daily updated information.
