### ISSUE TITLE
have configured groupid in default component whitelist but versioneye isn't respecting the setting

### ISSUE THREAD

**Issue by andyglick** [versioneye/versioneye#669]
I believe that I have followed the directions for creating a component whitelist, I added the groupId org.apache.bcel to the whitelist that I set as the default whitelist, but versioneye continues to report that the org.apache.bcel:bcel component is out of date -- this seems like a defect

you can fine the project on the versioneye site here https://www.versioneye.com/user/projects/570d35bffcd19a0045440b35

**Comment by andyglick** [comment]
I have since discovered that 1 can associate a component whitelist with a project via the project's settings configuration screen. I have now associated the default component whitelist to the cucumber-spring-eclipselink project, but versioneye is still reporting an out of date org.apache.bcel:bcel:3.0.0 and therefore seems to be ignoring the settings in the default whitelist

**Comment by reiz** [comment]
Hi @andyglick. The component whitelist is there to whitelist components which would otherwise violate a license whitelist. It's not taken into account for out-dated versions. 

If you don't want to get notified about an out-dated dependency, then you can mute a version. Here is a blog post to that.
