### ISSUE TITLE
 datatables.net-buttons-bs wrong version 2.2.0

### ISSUE THREAD

**Issue by ickbinhier** [versioneye/versioneye#677]
datatables.net-buttons-bs has no version 2.2.0. The latest version is the 1.3.1

Can you fixit.

**Comment by reiz** [comment]
Fixed now. See here: https://www.versioneye.com/css/datatables:datatables.net-buttons-bs/1.3.1. It seems they accidentally released a tag 2.2.0 and removed it again. We had even a link to the tarball into that repo.
