### ISSUE TITLE
Newtonsoft.Json license is MIT, please update

### ISSUE THREAD

**Issue by michaelkruglos** [versioneye/versioneye#678]
Take a look at [LICENSE.md](https://github.com/JamesNK/Newtonsoft.Json/blob/master/LICENSE.md) and please update.

**Comment by timgluz** [comment]
@reiz i have made LicenseCrawlers for that issue, seems we must add worker that translates Nuget's license URL into SPDX ids

**Comment by reiz** [comment]
@timgluz Yes. We have to bring that code on production.

**Comment by reiz** [comment]
@michaelkruglos The package Newtonsoft.JSON has already the MIT license on VersionEye. See here: https://www.versioneye.com/csharp/Newtonsoft.Json/10.0.2. Or what do you mean? Can you share more details?

**Comment by michaelkruglos** [comment]
@reiz it didn't have this information when I was looking at it. Thanks for the fix!
