### ISSUE TITLE
Please add ISC to the default license whitelist

### ISSUE THREAD

**Issue by g2p** [versioneye/versioneye#679]
ISC is equivalent to MIT, which is on the whitelist.

**Comment by reiz** [comment]
@g2p OK. Makes sense. Will be added today.

**Comment by reiz** [comment]
@g2p It's added now and it's deployed to production. But this change doesn't affect already existing license whitelists. For your own license whitelist please add the `ISC` string to it. New created organisations will get a default_lwl which contains the ISC license.
