### ISSUE TITLE
Add parser for Golang Glide package manager

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye#680]
Here's official repo for it: https://github.com/Masterminds/glide

This is how it looks a like: https://github.com/Masterminds/glide/blob/master/glide.yaml

It'll be deprecated as soon as stable version of `Dep` pkg-manager will be released, but it may take couple of years, but we require it for our Go crawlers.

**Comment by timgluz** [comment]
Done, except `parse_requested_version`, which waits to refactored in parent `Godeps` class

But it's functional enough for `GodepsGithubCrawler` to fetch dependency details.

**Comment by reiz** [comment]
@timgluz I merged your PR. It's part of the core now.
