### ISSUE TITLE
New plan purchased with one user not showing in another

### ISSUE THREAD

**Issue by Nir-Tal** [versioneye/versioneye#681]
My manager changed our plan to a paid one but when I'm entering version eye with me account it's still on the free plan. Any idea?

**Comment by reiz** [comment]
Hi @Nir-Tal. The plans are always bound to a VersionEye organisation. I guess he bought the plan in an organisation where you are not part of. Can you share the name of the organisation where your manager paid the plan?

**Comment by reiz** [comment]
@Nir-Tal You can be member of multiple organisations. By visiting this link http://www.versioneye.com/organisations/ you get a list of all organisations where you are part of. Maybe you are just looking in the wrong organisation.

**Comment by Nir-Tal** [comment]
The organisation is architrave-de, It's the only organisation we use.

**Comment by reiz** [comment]
Hi @Nir-Tal. The names for organisations at VersionEye are case sensitive. There are 2 orgas: 

https://www.versioneye.com/organisations/architrave-de/
https://www.versioneye.com/organisations/Architrave-de/

The last one is the right one. It contains the plan, team members and projects. 
Should I delete the first one? To avoid further confusion?
