### ISSUE TITLE
Licence unknown for php extensions

### ISSUE THREAD

**Issue by NicolasCARPi** [versioneye/versioneye#682]
Hello,

Would it be possible to make the PHP extensions ignored from the composer.json file?

Because right know their licence is unknown and it makes the check fail. See https://www.versioneye.com/pullrequests/5940df586725bd0079e5d4a5 for example.

![2017-06-14-120425_791x539_scrot](https://user-images.githubusercontent.com/3043706/27127011-b0809722-50f9-11e7-909c-1464ee21ce54.png)

Cheers :)

**Comment by reiz** [comment]
Hi @NicolasCARPi. I will put them on the ignore list today as a quick solution. But do you know what the licenses for PHP extensions are? Or is it always a different license?

**Comment by NicolasCARPi** [comment]
Hello @reiz, I think it's safe to bet they are all with PHP licence 3.01. ([source](http://news.php.net/php.internals/99503))

**Comment by reiz** [comment]
HI @NicolasCARPi. Thanks for the fast response and the link.  

I just ignored them with this commit: https://github.com/versioneye/versioneye-core/commit/345d46f9421057bcf96b8df55a2a434e942f26eb.

**Comment by reiz** [comment]
@NicolasCARPi The changes are deployed to production, but that doesn't affect already existing commits in pull requests. You will notice the change for new commits.

**Comment by reiz** [comment]
@NicolasCARPi Are PHP extensions something you ship with your application? Or do they exist already on the host, or the target system? 

In Java/Maven there is a scope `provided`. That describes dependencies which are not shipped & bundled with the application but the application expects that this dependencies exist already in the Application server or somewhere else in the classpath. Are PHP extensions similar?

**Comment by NicolasCARPi** [comment]
I ship with Docker, and extensions are inside the image. But if you install it without Docker, the composer.json file makes sure you have the necessary extensions before populating `vendor`.

Thanks for the fix! :)
