### ISSUE TITLE
Licences for rspec-retry and powder

### ISSUE THREAD

**Issue by makaroni4** [versioneye/versioneye#684]
Hi there 🍻 

Could you please fix licences for [powder](https://github.com/powder-rb/powder/blob/master/LICENSE) and [rspec-retry](https://github.com/NoRedInk/rspec-retry/blob/master/LICENSE)?

They are both MIT (check links).

🙏

**Comment by reiz** [comment]
It's fixed now. I even send out pull requests to fix it permanently for future releases: https://github.com/powder-rb/powder/pull/133.
