### ISSUE TITLE
language pages for Rust, Elixir are missing details section;

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye#685]
Rust and Elixir pages should have similar data as Ruby - https://www.versioneye.com/ruby/

**Comment by timgluz** [comment]
As we will have soon product page for Perl also, then may be it makes sense to add required data for `Perl` to

**Comment by timgluz** [comment]
Done, i added new languages through admin interface.

* Rust - https://www.versioneye.com/rust
* Elixir - https://www.versioneye.com/elixir
* Perl - https://www.versioneye.com/perl

**Comment by reiz** [comment]
Looks good to me.
