### ISSUE TITLE
Newest version for dotnet core nugets appear to be previews

### ISSUE THREAD

**Issue by michaelkruglos** [versioneye/versioneye#688]
Newest version column for dotnet core dependencies, like `Microsoft.AspNetCore.Authentication`, are preview versions.

![screen shot 2017-07-09 at 15 28 35](https://user-images.githubusercontent.com/3526988/27993944-948a26c0-64bb-11e7-89a1-3c574da84f54.png)

**Comment by timgluz** [comment]
Thanks for reporting - i will look into it.

**Comment by reiz** [comment]
@michaelkruglos By default VersionEye takes only the newest **stable** version into account. If a version is stable or not is decided by the [naturalsorter](https://github.com/versioneye/naturalsorter) project. I assume that version `2.0.0-preview2-final` is not stable. Right? In that case I will add a rule to recognise `-preview*` versions as unstable.

**Comment by timgluz** [comment]
Yep, according to their docs, `/preview\d+/` is pre-release and `preview-final` means that this preview is frozen: https://github.com/bleroy/core-docs/blob/dotnet/build-from-source/docs/core/building/distribution-packaging.md#preview-versions

**Comment by reiz** [comment]
@timgluz so `preview-final` means it's forzen? But it seems they number up as they are funny with `preview2-final` and then you can never be sure if they start another one with `preview3-*`. Sounds totally inconsistent.

**Comment by timgluz** [comment]
no, it means preview "branch" is frozen, but they can always release `preview2`, `preview3`, but there'll be no other releases on `preview` as this is closed now; 

think that `previewX` is somekind of milestone / branch; and it's unstable; aka more info on their docs;

**Comment by michaelkruglos** [comment]
My understanding is that you're going to mark these versions as preview and not suggest to upgrade to these versions, right?

**Comment by reiz** [comment]
@michaelkruglos Yes. That's the plan. Should be finished today.

**Comment by reiz** [comment]
@michaelkruglos Should be resolved now. `preview` versions are categorised as not stable now. Please double check your project. If somewhere still a preview version is offered as newest, then click the re parse button. /cc @timgluz
