### ISSUE TITLE
domain_name appears as outdated

### ISSUE THREAD

**Issue by ylecuyer** [versioneye/versioneye#689]
Dependency | Resolved | Newest
domain_name | 0.5.20170404 | 0.5.25

Newest is : 0.5.20170404

**Comment by reiz** [comment]
@ylecuyer can you share a link to your project?

**Comment by ylecuyer** [comment]
There is the version eye project: https://www.versioneye.com/user/projects/593b69d9368b08004e5145bb?child=summary

The github project is ylecuyer/events

**Comment by reiz** [comment]
I close this ticket because I opened a new feature request ticket on this repo: https://github.com/versioneye/naturalsorter/issues/12. That's there it belongs to.

**Comment by reiz** [comment]
@ylecuyer For right now I would recommend to use the mute feature in VersionEye to ignore this timestamp versions. Here is an article to that: https://blog.versioneye.com/2015/07/22/improved-mute-feature-2/.

**Comment by reiz** [comment]
@ylecuyer I just deployed the new updates. It seems to work. See here: https://www.versioneye.com/ruby/domain_name/0.5.20170404.
