### ISSUE TITLE
expose Perl submodules on the product page;

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye#693]
Each Perl package has 1 or many submodules and we should expose them on the product page, otherwise users may be confused why they see package page, when they clicked on the submodule  name;

Example:

Main module: https://www.versioneye.com/perl/Dist::Zilla/6.010
Submodule: https://www.versioneye.com/perl/Dist::Zilla::Plugin::Run::AfterRelease/6.010

**Comment by timgluz** [comment]
Done, i can see them now - but one thing makes me sad: some packages may include modules that share no common part with main_module; But it is just very special case;

**Comment by reiz** [comment]
@timgluz that's not something we can fix. Right? Looks like they don't followed name conventions.

**Comment by timgluz** [comment]
We can fix it - we could index the root of module names and then add a fallback function that looks up by those roots, but there's another edge case lurking - what if module names are overlapping / conflicting with others, which package to select then. 

But i recommend to keep kicking this can down the road until we have paying customer for the feature;
