### ISSUE TITLE
incorrect latest version of perl

### ISSUE THREAD

**Issue by chorny** [versioneye/versioneye#695]
https://www.versioneye.com/perl/Apache::Session/1.93 shows "5.00503" as newest version of perl. Correct value is 5.26.0 (or 5.026000).

**Comment by reiz** [comment]
@chorny On metacpan 1.93 is the newest. Just like marked at VersionEye. I can't see a "5.26.0" version. Can you share a link to that?

**Comment by timgluz** [comment]
He means the version of the `perl` on the dependency list and he's right; seems that the crawler hasn't paginate all over the data; link: https://www.versioneye.com/perl/perl/5.00503 and link on the cpan: https://metacpan.org/pod/perl

**Comment by timgluz** [comment]
Ok, crawler seems to be fine - issue is that newest Perl is released under module name `open`, and not Perl; https://www.versioneye.com/perl/open/5.027000

I'll try to find any solution that could solve inconsistencies between `name`, `distribution`, `main_module` and etc field they are exposing via release API;

**Comment by reiz** [comment]
OK. It's updated. The newest Perl version is https://www.versioneye.com/perl/perl/5.027000.

**Comment by timgluz** [comment]
Can you also pull links & license details from `perl/open` product?

 Thanks

**Comment by reiz** [comment]
Will do later today.

**Comment by reiz** [comment]
done.
