### ISSUE TITLE
Wrong newest dependency for FOSUserBundle

### ISSUE THREAD

**Issue by ronisaha** [versioneye/versioneye#701]
Hi, 
In my [project ](https://www.versioneye.com/user/projects/545c7e4666df332df8000008) its showing the newest dependency for friendsofsymfony/user-bundle as **dev-test-interface**. What does that means. there is no such version for that package. 
![Image](http://i.imgur.com/1QrCl0w.png)

**Comment by reiz** [comment]
It's fixed now.
