### ISSUE TITLE
Can't import a project I own

### ISSUE THREAD

**Issue by Mahmoudz** [versioneye/versioneye#702]
I renamed the repository. And since then there's no way I can re-import that project. Tried disconnecting and reconnection not working. 

Trying to import [this](https://github.com/apiato/apiato) project.

My username is `Mahmoudz`. Any help? 

Thanks,

**Comment by reiz** [comment]
Hi @Mahmoudz. Can you send a link to your VersionEye organisation please?

**Comment by reiz** [comment]
@Mahmoudz In the GitHub page, did you click already the "Reimport all repositories" link? 

![screen shot 2017-08-10 at 16 51 31](https://user-images.githubusercontent.com/652130/29176610-95cdc7d6-7dec-11e7-839f-2447b837863d.png)

**Comment by Mahmoudz** [comment]
@reiz yes I did many times, it imports all projects except the one I need, which lives in a different organization.

**Comment by helgaw** [comment]
I'm experiencing the same problem.  My github account has two organizations and I only see projects from one of them, which is not the one I need to use.

**Comment by Mahmoudz** [comment]
@helgaw the only solution that worked with me after loooong time, is importing the project by by URL, and pointing to your composer.json file example `https://github.com/apiato/apiato/blob/master/composer.json`.
