### ISSUE TITLE
Python / PyPI scraper not updating

### ISSUE THREAD

**Issue by jpiorkowski** [versioneye/versioneye#703]
Hi, thanks for the service.

I am trying to use it for our Python projects and noticed that Python integration might have broken around middle of July. Some things I noticed:

- On https://www.versioneye.com/Python there is no record of packages being updated after 16 July 2017, while https://www.versioneye.com/nodejs has packages updated on 10 August:

![screenshot_2017-08-11_21-35-58](https://user-images.githubusercontent.com/24873181/29229445-bdeebb88-7ede-11e7-9c3a-14a5f06b085a.png)

- https://www.versioneye.com/python/boto3 redirects to https://www.versioneye.com/python/boto3/1.4.4 while PyPI has 1.4.5 (released 1 August); https://www.versioneye.com/python/boto3/1.4.5 exists but specifies unknown license

- "Most referenced libraries" section on https://www.versioneye.com/Python all show 0 references, while on /nodejs most referenced is Mocha with 85156 references:

![screenshot_2017-08-11_21-44-27](https://user-images.githubusercontent.com/24873181/29229650-d9682c2c-7edf-11e7-9279-ed00c0af81c6.png)

- transitive references don't seem to resolve for Python projects; all of our projects are private so I can't really link to an example, but POST to https://www.versioneye.com/user/projects/[redacted]/transitive_dependencies just returns:

`jQuery('#trans_deps').html('\n\n\n<table class=\"dependency_table\">\n  <thead>\n    <tr>\n      <th style=\"padding-left: 5px;\" >Dependency<\/th>\n      <th style=\"padding-left: 5px;\" >License<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>\n<br/><br/>\n\n\n\n');
document.getElementById('progress_bar').style.display='none';`

I searched the issue tracker but didn't find anything. Is it a known issue?

**Comment by reiz** [comment]
Hi @jpiorkowski The Pypi API changed recently and we needed some time to adjust our crawlers. It's fixed now.
