### ISSUE TITLE
SWT 3.105.3 not showing up in search results

### ISSUE THREAD

**Issue by alex3kov** [versioneye/versioneye#705]
I submitted this URL https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.swt.gtk.linux.x86_64/3.105.3/ (apparently Eclipse has some new versioning scheme going).  
It was pointed out to me that it's already available at https://www.versioneye.com/java/org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64/3.105.3. The link is working, but if searching for "swt" in Java - version 3.105.3 is not in the results.

**Comment by reiz** [comment]
@alex3kov You are right. Our search engine is ElasticSearch. It's a complex tool and I guess nobody understands fully how it works. Better you use Google for search. Did you know that you can limit the Google search to a specific domain? If you type in: `site:versioneye.com org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64 3.105.3` Google will search for your keyword only on VersionEye pages and then you get the right results. See [here](https://www.google.de/search?source=hp&q=site%3Aversioneye.com+org.eclipse.platform%3Aorg.eclipse.swt.gtk.linux.x86_64+3.105.3&oq=site%3Aversioneye.com+org.eclipse.platform%3Aorg.eclipse.swt.gtk.linux.x86_64+3.105.3&gs_l=psy-ab.3...2033.14889.0.15733.28.25.1.0.0.0.193.2241.19j6.25.0....0...1.1.64.psy-ab..4.5.452.0..0j46j35i39k1j0i46k1.isyUls8R_Qk).

**Comment by alex3kov** [comment]
Yeah, I know about google's site-specific search. Tried it out with your site - it still doesn't show latest (3.105.3) version when searched for just "swt". 2 notes here:  
* Coming up with a serch term "org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64" wouldn't be my first guess;
* If your search engine is broken, why not get rid of it and outsorce the search somewhere else entirely? :)
