### ISSUE TITLE
Invalid security violation on tough-cookie

### ISSUE THREAD

**Issue by avindra** [versioneye/versioneye#720]
Here, you can see a PR where `tough-cookie` `2.3.3` is being reported as in violation:

![image](https://user-images.githubusercontent.com/126848/31131375-ffc84e30-a827-11e7-85ea-47d4146713a3.png)

On the versioneye page for [tough-cookie](https://www.versioneye.com/Node.JS/tough-cookie/2.3.3), you can see:

> Recommendation: Please update to version 2.3.3 or greater

Despite this recommendation, veye is still flagging `2.3.3` as insecure.

---

The release has been out for a few days now, so I would imagine veye's database should be up to date by now?

**Comment by reiz** [comment]
@avindra Yes. That looks like a bug. I check it right now.

**Comment by reiz** [comment]
It's fixed now: https://www.versioneye.com/Node.JS/tough-cookie/2.3.3.
